name : Deploy React App Distribution
on: [push, workflow_dispatch, pull_request]
#on: push: branches: [main] # to trigger workflow only on main branch push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying React App Distribution"
        uses: actions/checkout@v4
      - name: "Install node using marketplace"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: check node version
        run: node -v
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # we create cache folder and give the key to that fplder so that next time when the workflow runs it can check if there is new dependencies to be installed or not it is check 
          # by comparing the key if there is no change in key it will use the cached version cached version will speed up the workflow run time
          # the key is generated using the hash of package-lock.json file if there is any change in the file the hash will change and new dependencies will be installed
      - name: install dependencies
        run: npm Install

      - name : build project
        run: npm run build
        
      - name: build completed
        run: echo "build completed"
        
      - name: upload build artifcat
        uses: actions/upload-artifact@v4
        with:
          name: react-app-dist
          path: ./dist
          #Artifacts are uploaded to GitHub’s storage so you (or other jobs) can use the output of your workflow later.

      

  deploy:
    needs: build  # This job depends on the 'deploy' job to complete first otherwise both will run parllelly
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying React App Distribution"
        uses: actions/checkout@v4

      - name: "Install node using marketplace"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: check node version
        run: node -v

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm install

      - name : build project
        run: npm run build

      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app-dist
          path: ./dist

      - name: build completed
        run: echo "build completed"


#can use pre built actions like actions/checkout@v4 from marketplace github actions
#to prevent workflow trigger on comments  on ccommit message ad this [skip ci] or [ci skip]